export {
  canPayResourceCosts,
  clearCooldown,
  cooldownRemaining,
  createActionGraceState,
  createCooldownState,
  createGameplayActionState,
  createResolutionEvidenceTracker,
  createResourcePoolState,
  gainResource,
  getResourcePool,
  getResourceRatio,
  getElapsedCooldownStatus,
  isCooldownReady,
  payResourceCosts,
  resolveHudGauge,
  setResourceValue,
  startCooldown,
  stepActionGrace,
  stepCooldownState,
  stepGameplayActionState,
  stepResourcePools,
  tryStartCooldown,
  tryStartGameplayAction,
} from '../../vendor/arcade-runtime.mjs';
