export {
  canPayResourceCosts,
  clearCooldown,
  cooldownRemaining,
  createActionGraceState,
  createCooldownState,
  createGameplayActionState,
  createResolutionEvidenceTracker,
  createResourcePoolState,
  gainResource,
  getResourcePool,
  getResourceRatio,
  getElapsedCooldownStatus,
  isCooldownReady,
  payResourceCosts,
  resolveHudGauge,
  setResourceValue,
  startCooldown,
  stepActionGrace,
  stepCooldownState,
  stepGameplayActionState,
  stepResourcePools,
  tryStartCooldown,
  tryStartGameplayAction,
} from '../../vendor/arcade-runtime.d.mts';

export type {
  ArcadeActionGraceEvent,
  ArcadeActionGraceState,
  ArcadeGameplayActionDefinition,
  ArcadeGameplayActionEvent,
  ArcadeGameplayActionState,
  ArcadeResourceCost,
  ArcadeResourceEvent,
  ArcadeResourceEventKind,
  ArcadeResourcePool,
  ArcadeResourcePoolInput,
  ArcadeResourcePoolState,
  ArcadeResolutionEvidenceBase,
  ArcadeResolutionEvidenceSnapshot,
  CooldownState,
} from '../../vendor/arcade-runtime.d.mts';
