export {
  ARCADE_PIXI_RUNTIME_VERSION,
  DEFAULT_ARCADE_LAYERS,
  createArcadeCameraTransform,
  createArcadeFrameProfiler,
  createArcadePixiRuntime,
  createCanvasTexturePass,
  createCanvasTexturePassOptions,
  createPixiSceneGraph,
  createPixiFramePool,
  createPixiHudGauge,
  createPixiSpritePool,
  defineArcadeRenderPlan,
  installArcadeRenderPlan,
} from '../../vendor/arcade-runtime.d.mts';

export type {
  ArcadeCameraState,
  ArcadeCameraTransform,
  ArcadeFrameProfiler,
  ArcadePerformanceSummary,
  ArcadePixiFrame,
  ArcadePixiFramePoolSnapshot,
  ArcadePixiHudGaugeLayout,
  ArcadePixiHudGaugeStyle,
  ArcadePixiNamespace,
  ArcadePixiPassContext,
  ArcadePixiPassHandle,
  ArcadePixiPassOptions,
  ArcadePixiRuntime,
  ArcadePixiRuntimeOptions,
  ArcadePixiTelemetry,
  ArcadeRenderPlanEntry,
  CanvasTexturePassOptions,
  CanvasTexturePassState,
} from '../../vendor/arcade-runtime.d.mts';
