// @arcade/runtime/sprites — type declarations mirrored from reference src/sprites.d.ts
export type {
  ArcadeSpriteAnimation,
  ArcadeSpriteAnimationEvent,
  ArcadeSpriteBox,
  ArcadeSpriteCanvasContext,
  ArcadeSpriteCanvasDrawOptions,
  ArcadeSpriteCanvasPlacement,
  ArcadeSpriteClip,
  ArcadeSpriteCompiledFrame,
  ArcadeSpriteContactSheetCell,
  ArcadeSpriteContactSheetDrawOptions,
  ArcadeSpriteContactSheetEntry,
  ArcadeSpriteContactSheetLayout,
  ArcadeSpriteContactSheetLayoutOptions,
  ArcadeSpriteContactSheetOptions,
  ArcadeSpriteContactSheetRenderEntry,
  ArcadeSpriteContactSheetRenderResult,
  ArcadeSpriteFrameAddress,
  ArcadeSpriteFrameCache,
  ArcadeSpriteFrameGeometry,
  ArcadeSpriteFrameInspection,
  ArcadeSpriteFrameTransform,
  ArcadeSpriteGrid,
  ArcadeSpriteInspectableAtlas,
  ArcadeSpriteInspectableFrame,
  ArcadeSpriteInspectionOptions,
  ArcadeSpriteManifest,
  ArcadeSpriteManifestIndex,
  ArcadeSpriteManifestSource,
  ArcadeSpritePixelData,
  ArcadeSpritePixelRectangle,
  ArcadeSpritePixelSource,
  ArcadeSpriteSheet,
  ArcadeSpriteVisibleScaleOptions,
} from '../../vendor/arcade-runtime.d.mts';
export {
  collectArcadeSpriteAnimationEvents,
  compileArcadeSpriteClip,
  createArcadeSpriteContactSheetLayout,
  createArcadeSpriteFrameGeometry,
  createArcadeSpriteManifestIndex,
  drawArcadeSpriteCanvas,
  drawArcadeSpriteCanvasFrame,
  drawArcadeSpriteContactSheetCanvas,
  inspectArcadeSpriteFrame,
  normalizeArcadeSpriteManifest,
  resolveArcadeSpriteVisibleScale,
  resolveArcadeSpriteFrame,
  validateArcadeSpriteManifest,
} from '../../vendor/arcade-runtime.d.mts';
