// @arcade/runtime/stages — type declarations mirrored from reference src/stages.d.ts
export {
  advanceEncounter,
  advanceStageGraph,
  createEncounterPlan,
  createEncounterState,
  createStageGraph,
  createStageGraphState,
  getCurrentEncounter,
  getCurrentStageNode,
  getStageNode,
  inspectEncounterState,
  inspectStageGraphState,
  installStageServices,
  validateEncounterPlan,
  validateStageGraph,
} from '../../vendor/arcade-runtime.d.mts';
export type {
  ArcadeEncounter,
  ArcadeEncounterDefinition,
  ArcadeEncounterPlan,
  ArcadeEncounterPlanDefinition,
  ArcadeEncounterState,
  ArcadeStageGraph,
  ArcadeStageGraphDefinition,
  ArcadeStageGraphState,
  ArcadeStageIssue,
  ArcadeStageNode,
  ArcadeStageNodeDefinition,
  ArcadeStageReferenceCatalogs,
  ArcadeStageServiceInstallation,
  ArcadeStageServiceInstaller,
  ArcadeStageServiceScope,
  ArcadeStageTransition,
  ArcadeStageTransitionDefinition,
} from '../../vendor/arcade-runtime.d.mts';
