// @arcade/runtime/ui — type declarations mirrored from reference src/ui.d.ts
export {
  ARCADE_UI_FONT,
  ARCADE_UI_UNIT,
  DEFAULT_ARCADE_UI_THEME,
  createAccessibilityPreferences,
  createArcadeNoticeQueue,
  createArcadeUiTheme,
  createFocusNavigator,
  createGridFocusNavigator,
  createInputHintTracker,
  createMessageCatalog,
  createTextMeasureCache,
  createUiNavigationRepeater,
  drawArcadeBackdropCanvas,
  drawArcadeChipCanvas,
  drawArcadeCommandBarCanvas,
  drawArcadeFooterCanvas,
  drawArcadeMenuRowCanvas,
  drawArcadeMeterCanvas,
  drawArcadeNoticeCanvas,
  drawArcadePanelCanvas,
  drawArcadeScreenTitleCanvas,
  drawArcadeTextBlockCanvas,
  fitArcadeTextCanvas,
  resolveArcadeCommandHints,
  resolveGridFocusIndex,
  resolveHudGauge,
  resolveSafeAreaLayout,
  wrapArcadeTextCanvas,
} from '../../vendor/arcade-runtime.d.mts';
export type {
  ArcadeChipOptions,
  ArcadeCommandAction,
  ArcadeCommandDevice,
  ArcadeCommandHintInput,
  ArcadeMeterOptions,
  ArcadeNotice,
  ArcadeNoticeInput,
  ArcadeNoticeKind,
  ArcadePanelOptions,
  ArcadeResolvedCommandHint,
  ArcadeScreenTitleOptions,
  ArcadeTextLayout,
  ArcadeUiCanvasContext,
  ArcadeUiTheme,
} from '../../vendor/arcade-runtime.d.mts';
