import type { ItemDefinition } from './InventorySystem';

export const CORE_ITEM_SHEET_ID = 'items_core';
export const CORE_ITEM_ICON_SHEET_ID = 'item_icons';
export const EXTENDED_ITEM_SHEET_ID = 'items_extended';
export const EXTENDED_ITEM_ICON_SHEET_ID = 'item_icons_extended';

const coreItem = (item: ItemDefinition): ItemDefinition => ({
	...item,
	iconSheetId: item.iconSheetId ?? CORE_ITEM_ICON_SHEET_ID,
	pickupSheetId: item.pickupSheetId ?? CORE_ITEM_SHEET_ID,
	pickupAnimation: item.pickupAnimation ?? `${item.id}_pickup`,
});

const extendedItem = (item: ItemDefinition): ItemDefinition => ({
	...item,
	iconSheetId: EXTENDED_ITEM_ICON_SHEET_ID,
	pickupSheetId: EXTENDED_ITEM_SHEET_ID,
	pickupAnimation: `${item.id}_pickup`,
});

export const FIRST_RELEASE_ITEM_CATALOG: readonly ItemDefinition[] = [
	coreItem({
		id: 'rocket_backpack',
		name: 'Rocket Backpack',
		slot: 'active',
		rarity: 'core',
		tags: ['movement', 'fuel'],
		effect: 'Directional burst; recharges on ground and with fuel cells.',
		iconAnimation: 'rocket_backpack_icon',
	}),
	coreItem({
		id: 'railgun',
		name: 'Railgun',
		slot: 'weapon',
		rarity: 'core',
		tags: ['ranged', 'timing'],
		effect: 'Heavy piercing shot with reload cadence and recoil.',
		iconAnimation: 'railgun_icon',
	}),
	coreItem({
		id: 'stim_pack',
		name: 'Stim Pack',
		slot: 'consumable',
		rarity: 'core',
		tags: ['heal', 'focus'],
		effect: 'Heal and briefly slow perceived time.',
		iconAnimation: 'stim_pack_icon',
		maxStack: 6,
	}),
	coreItem({
		id: 'claws',
		name: 'Claws',
		slot: 'melee',
		rarity: 'starter',
		tags: ['melee', 'parry'],
		effect: 'Fast slash; parry during enemy flash.',
		iconAnimation: 'claws_icon',
	}),
	coreItem({
		id: 'katana',
		name: 'Katana',
		slot: 'melee_upgrade',
		rarity: 'rare',
		tags: ['melee', 'perfect'],
		effect: 'Draw slash after parry or perfect dodge.',
		iconAnimation: 'katana_icon',
	}),
	coreItem({
		id: 'signal_jammer',
		name: 'Signal Jammer',
		slot: 'active',
		rarity: 'uncommon',
		tags: ['hack', 'stealth'],
		effect: 'Freezes cameras, slows drones, and hides hack traces.',
		iconAnimation: 'signal_jammer_icon',
		effects: { traceReduction: 0.1, beatGrace: 0.025 },
	}),
	coreItem({
		id: 'phase_pick',
		name: 'Phase Pick',
		slot: 'utility',
		rarity: 'uncommon',
		tags: ['heist', 'secret'],
		effect: 'Opens weak walls and keeps action chains alive through interactions.',
		iconAnimation: 'phase_pick_icon',
		effects: { comboWindowBonus: 0.06 },
	}),
	coreItem({
		id: 'dub_shield',
		name: 'Dub Shield',
		slot: 'defense',
		rarity: 'rare',
		tags: ['beat', 'guard'],
		effect: 'Beat-synced pulse absorbs part of incoming damage.',
		iconAnimation: 'dub_shield_icon',
		effects: { damageMitigation: 0.08, beatGrace: 0.035 },
	}),
	coreItem({
		id: 'echo_cassette',
		name: 'Echo Cassette',
		slot: 'boon',
		rarity: 'rare',
		tags: ['decoy', 'run'],
		effect: 'A perfect dodge leaves a replay ghost in the enemy targeting loop.',
		iconAnimation: 'echo_cassette_icon',
		effects: { decoyOnPerfectDodge: true },
	}),
	coreItem({
		id: 'gravity_talisman',
		name: 'Gravity Talisman',
		slot: 'movement',
		rarity: 'rare',
		tags: ['air', 'flip'],
		effect: 'Bends fall speed and aerial steering.',
		iconAnimation: 'gravity_talisman_icon',
	}),
	coreItem({
		id: 'nanofur_weave',
		name: 'Nanofur Weave',
		slot: 'passive',
		rarity: 'uncommon',
		tags: ['armor', 'fur'],
		effect: 'Reduces spike, graze, and contact damage.',
		iconAnimation: 'nanofur_weave_icon',
		effects: { damageMitigation: 0.08 },
	}),
	coreItem({
		id: 'solder_mite_swarm',
		name: 'Solder Mite Swarm',
		slot: 'companion',
		rarity: 'rare',
		tags: ['repair', 'armor'],
		effect: 'Repairs rocket cells and tunes weapon contacts.',
		iconAnimation: 'solder_mite_swarm_icon',
		effects: { fuelRechargeBonus: 0.15, railDamageBonus: 0.1 },
	}),
	coreItem({
		id: 'black_ice_tooth',
		name: 'Black Ice Tooth',
		slot: 'hack_combat',
		rarity: 'epic',
		tags: ['hack', 'emp'],
		effect: 'Code-gate charge hardens parry counters and rail EMP payloads.',
		iconAnimation: 'black_ice_tooth_icon',
		effects: { hackChargesMelee: true, parryDamageBonus: 0.25, empOnChargedShot: true },
	}),
	coreItem({
		id: 'bassline_boots',
		name: 'Bassline Boots',
		slot: 'movement',
		rarity: 'uncommon',
		tags: ['beat', 'landing'],
		effect: 'Landing on beat creates a shockwave.',
		iconAnimation: 'bassline_boots_icon',
	}),
	coreItem({
		id: 'contraband_seed_key',
		name: 'Contraband Seed Key',
		slot: 'meta',
		rarity: 'legendary',
		tags: ['shop', 'meta'],
		effect: 'Unlocks a hidden shop category across runs.',
		iconAnimation: 'contraband_seed_key_icon',
	}),
	extendedItem({
		id: 'capacitor_coil',
		name: 'Mutual-Aid Capacitor',
		slot: 'passive',
		rarity: 'rare',
		tags: ['railgun', 'charge'],
		effect: 'Adds rail damage and pushes one more target through the sightline.',
		iconAnimation: 'capacitor_coil_icon',
		effects: { railDamageBonus: 0.2, railPierceBonus: 1 },
	}),
	extendedItem({
		id: 'phase_mantle',
		name: 'Phase Mantle',
		slot: 'defense',
		rarity: 'rare',
		tags: ['dodge', 'guard'],
		effect: 'Thins incoming hits and cycles the dodge relay faster.',
		iconAnimation: 'phase_mantle_icon',
		effects: { damageMitigation: 0.1, dodgeCooldownReduction: 0.08 },
	}),
	extendedItem({
		id: 'ledger_lens',
		name: 'Ledger Lens',
		slot: 'utility',
		rarity: 'uncommon',
		tags: ['combo', 'evidence'],
		effect: 'Keeps the combat chain legible long enough to finish the audit.',
		iconAnimation: 'ledger_lens_icon',
		effects: { comboWindowBonus: 0.14, meleeStyleBonus: 1 },
	}),
	extendedItem({
		id: 'echo_spurs',
		name: 'Echo Spurs',
		slot: 'movement',
		rarity: 'uncommon',
		tags: ['air', 'beat'],
		effect: 'Adds aerial correction and accelerates grounded fuel recovery.',
		iconAnimation: 'echo_spurs_icon',
		effects: { airControlBonus: 0.08, fuelRechargeBonus: 0.2 },
	}),
	extendedItem({
		id: 'rail_heat_sink',
		name: 'Rail Heat Sink',
		slot: 'passive',
		rarity: 'rare',
		tags: ['railgun', 'cooldown'],
		effect: 'Shortens rail recovery and absorbs most firing recoil.',
		iconAnimation: 'rail_heat_sink_icon',
		effects: { railCooldownReduction: 0.14, railRecoilReduction: 0.45 },
	}),
	extendedItem({
		id: 'rootkit_badge',
		name: 'Rootkit Union Badge',
		slot: 'hack_combat',
		rarity: 'epic',
		tags: ['hack', 'solidarity'],
		effect: 'Reduces trace and routes successful hacks into close combat.',
		iconAnimation: 'rootkit_badge_icon',
		effects: { traceReduction: 0.15, hackChargesMelee: true, parryDamageBonus: 0.2 },
	}),
	extendedItem({
		id: 'shock_fern',
		name: 'Shock Fern Cutting',
		slot: 'boon',
		rarity: 'rare',
		tags: ['emp', 'garden'],
		effect: 'Seeds rail impacts with a short EMP bloom.',
		iconAnimation: 'shock_fern_icon',
		effects: { empOnChargedShot: true, railDamageBonus: 0.12 },
	}),
	extendedItem({
		id: 'mirror_thread',
		name: 'Mirror Thread',
		slot: 'passive',
		rarity: 'epic',
		tags: ['parry', 'decoy'],
		effect: 'Widens the parry seam and leaves a false reflection after a dodge.',
		iconAnimation: 'mirror_thread_icon',
		effects: { parryWindowBonus: 0.025, decoyOnPerfectDodge: true },
	}),
];

export function getFirstReleaseItem(itemId: string): ItemDefinition | undefined {
	return FIRST_RELEASE_ITEM_CATALOG.find((item) => item.id === itemId);
}
