import type { SocialSpaceLayoutDef } from './SocialSpaceCatalog';

export const ANTENNA_BARRENS_SOCIAL_SPACES: readonly SocialSpaceLayoutDef[] = [
	{
		locationId: 'antenna-barrens:safehouse',
		width: 1880,
		floorY: 356,
		spawnX: 170,
		walkSpeed: 212,
		interactionRadius: 92,
		farLayer: 'Lightning walks between obsolete dishes beyond grounded storm shutters.',
		midLayer: 'Copper prayer strips, threat-model cabinets, mast tools, batteries, and listener cassettes fill the shelter.',
		anchors: [
			{ id: 'reverend-null-dial', kind: 'npc', x: 300 },
			{ id: 'signal-lab', kind: 'service', x: 500 },
			{ id: 'mara-modulo', kind: 'npc', x: 790 },
			{ id: 'skill-mentor', kind: 'service', x: 980 },
			{ id: 'calder-raincheck', kind: 'npc', x: 1270 },
			{ id: 'repair-bench', kind: 'service', x: 1460 },
			{ id: 'loadout-locker', kind: 'service', x: 1690 },
		],
		props: [
			{ id: 'radio-pulpit', kind: 'console', x: 230, width: 330, height: 156, label: 'CONSENT BEFORE REACH' },
			{ id: 'threat-cabinets', kind: 'archive', x: 700, width: 350, height: 168, label: 'PUBLIC / PROTECTED' },
			{ id: 'grounding-bench', kind: 'bench', x: 1210, width: 300, height: 104, label: 'LIGHTNING IS NOT EDGE' },
			{ id: 'faraday-locker', kind: 'archive', x: 1640, width: 130, height: 154, label: 'CREW GEAR' },
		],
	},
	{
		locationId: 'antenna-barrens:settlement',
		width: 2220,
		floorY: 358,
		spawnX: 180,
		walkSpeed: 214,
		interactionRadius: 94,
		farLayer: 'Weather tarps bridge broken dishes while static snow drifts against a black horizon.',
		midLayer: 'Clinic lamps, probability boards, cassette crates, appeal tables, and scavenged signal parts divide the camp.',
		anchors: [
			{ id: 'doctor-error-bar', kind: 'npc', x: 320 },
			{ id: 'clinic', kind: 'service', x: 510 },
			{ id: 'penny-static', kind: 'npc', x: 800 },
			{ id: 'archive', kind: 'service', x: 990 },
			{ id: 'mara-modulo', kind: 'npc', x: 1230 },
			{ id: 'maceo-margin', kind: 'npc', x: 1430 },
			{ id: 'legal-aid', kind: 'service', x: 1580 },
			{ id: 'rumor-board', kind: 'service', x: 1760 },
			{ id: 'black-ice-fox', kind: 'npc', x: 2020 },
		],
		props: [
			{ id: 'error-board', kind: 'archive', x: 240, width: 360, height: 164, label: 'THE OTHER EIGHT PERCENT' },
			{ id: 'listener-cache', kind: 'archive', x: 720, width: 340, height: 130, label: 'CHOSEN AUDIENCE' },
			{ id: 'appeal-table', kind: 'bench', x: 1370, width: 280, height: 100, label: 'DELAY AUTOMATION' },
			{ id: 'forecast-fox', kind: 'light', x: 1920, width: 210, height: 172, label: 'EXPECTED ≠ AUTHORED' },
		],
	},
	{
		locationId: 'antenna-barrens:station',
		width: 2100,
		floorY: 360,
		spawnX: 190,
		walkSpeed: 220,
		interactionRadius: 98,
		farLayer: 'Dish constellations and dead catenary towers frame a roofless platform under charged clouds.',
		midLayer: 'Arrival boards, grounded rails, suppressed-message lockers, mast carts, and public forecast consoles occupy the terminal.',
		anchors: [
			{ id: 'penny-static', kind: 'npc', x: 330 },
			{ id: 'archive', kind: 'service', x: 540 },
			{ id: 'calder-raincheck', kind: 'npc', x: 850 },
			{ id: 'transit-control', kind: 'service', x: 1060 },
			{ id: 'reverend-null-dial', kind: 'npc', x: 1320 },
			{ id: 'maceo-margin', kind: 'npc', x: 1510 },
			{ id: 'signal-lab', kind: 'service', x: 1690 },
			{ id: 'repair-bench', kind: 'service', x: 1870 },
		],
		props: [
			{ id: 'impossible-board', kind: 'light', x: 230, width: 380, height: 154, label: 'ARRIVAL + ASSUMPTIONS' },
			{ id: 'message-lockers', kind: 'archive', x: 700, width: 260, height: 140, label: 'SUPPRESSED SIGNALS' },
			{ id: 'forecast-console', kind: 'console', x: 980, width: 350, height: 176, label: 'METHOD / ERROR / APPEAL' },
			{ id: 'mast-cart', kind: 'bench', x: 1770, width: 240, height: 96, label: 'GROUND CREW' },
		],
	},
];
