import type { SocialSpaceLayoutDef } from './SocialSpaceCatalog';

export const ASTEROID_REDOUBT_SOCIAL_SPACES: readonly SocialSpaceLayoutDef[] = [
	{
		locationId: 'asteroid-redoubt:safehouse',
		width: 2020,
		floorY: 356,
		spawnX: 170,
		walkSpeed: 210,
		interactionRadius: 92,
		farLayer: 'Black ice and transmitter roots frame city-blue and colony-violet signal stars.',
		midLayer: 'Patched microphones, maintenance scores, root tools, masks, route proofs, and crew lockers fill the workshop.',
		anchors: [
			{ id: 'choir-of-static', kind: 'npc', x: 320 },
			{ id: 'signal-lab', kind: 'service', x: 560 },
			{ id: 'aunt-aster', kind: 'npc', x: 880 },
			{ id: 'repair-bench', kind: 'service', x: 1090 },
			{ id: 'skill-mentor', kind: 'service', x: 1340 },
			{ id: 'godel-archive-echo', kind: 'npc', x: 1510 },
			{ id: 'rook-null', kind: 'npc', x: 1660 },
			{ id: 'loadout-locker', kind: 'service', x: 1840 },
		],
		props: [
			{ id: 'temporary-solo', kind: 'console', x: 230, width: 410, height: 172, label: 'NO PERMANENT SOLOIST' },
			{ id: 'root-bench', kind: 'bench', x: 800, width: 340, height: 110, label: 'TEACH THE INTUITION' },
			{ id: 'maintenance-score', kind: 'archive', x: 1260, width: 300, height: 154, label: 'ARGUE HERE' },
			{ id: 'protected-proof', kind: 'archive', x: 1530, width: 250, height: 148, label: 'VISIBLE BLANK' },
		],
	},
	{
		locationId: 'asteroid-redoubt:settlement',
		width: 2400,
		floorY: 358,
		spawnX: 180,
		walkSpeed: 214,
		interactionRadius: 96,
		farLayer: 'The transmitter root rises through the commons toward a sky crowded with owned satellites.',
		midLayer: 'Toolkit cases, witness glass, protected maps, doctrine drafts, seed trays, and an empty executive chair circle the root.',
		anchors: [
			{ id: 'witness-zero', kind: 'npc', x: 320 },
			{ id: 'archive', kind: 'service', x: 520 },
			{ id: 'legal-aid', kind: 'service', x: 790 },
			{ id: 'little-ix', kind: 'npc', x: 1030 },
			{ id: 'della-redact', kind: 'npc', x: 1220 },
			{ id: 'rumor-board', kind: 'service', x: 1410 },
			{ id: 'greenhouse', kind: 'service', x: 1540 },
			{ id: 'choir-of-static', kind: 'npc', x: 1810 },
			{ id: 'director-vane', kind: 'npc', x: 2180 },
		],
		props: [
			{ id: 'toolkit-cases', kind: 'archive', x: 230, width: 400, height: 150, label: 'TOOLS / NO PORTRAIT' },
			{ id: 'responsibility-table', kind: 'bench', x: 700, width: 300, height: 104, label: 'COMPLICITY ≠ CENTER' },
			{ id: 'protected-map', kind: 'archive', x: 1040, width: 340, height: 166, label: 'PRESENT / PROTECTED' },
			{ id: 'vacuum-seeds', kind: 'greenery', x: 1460, width: 280, height: 154, label: 'CITY + COLONY CUTTINGS' },
			{ id: 'executive-chair', kind: 'bench', x: 2070, width: 220, height: 180, label: 'QUARTERLY REGRET' },
		],
	},
	{
		locationId: 'asteroid-redoubt:station',
		width: 2160,
		floorY: 360,
		spawnX: 190,
		walkSpeed: 220,
		interactionRadius: 98,
		farLayer: 'City-blue, colony-violet, and asteroid-white signal lamps hang over the dock against open space.',
		midLayer: 'Return windows, protected-route shutters, toolkit mirrors, seed containers, and maintenance beacons line the dock.',
		anchors: [
			{ id: 'return-signal-sam', kind: 'npc', x: 340 },
			{ id: 'transit-control', kind: 'service', x: 590 },
			{ id: 'little-ix', kind: 'npc', x: 850 },
			{ id: 'della-redact', kind: 'npc', x: 1030 },
			{ id: 'archive', kind: 'service', x: 1200 },
			{ id: 'aunt-aster', kind: 'npc', x: 1410 },
			{ id: 'repair-bench', kind: 'service', x: 1620 },
			{ id: 'signal-lab', kind: 'service', x: 1940 },
		],
		props: [
			{ id: 'three-lights', kind: 'light', x: 230, width: 430, height: 166, label: 'READY / REVISED / ASK AGAIN' },
			{ id: 'return-window', kind: 'train', x: 690, width: 370, height: 146, label: 'ANSWER ≠ OPEN ACCESS' },
			{ id: 'protected-shutter', kind: 'barrier', x: 1090, width: 230, height: 180, label: 'JUSTIFIED BLANK' },
			{ id: 'toolkit-mirror', kind: 'console', x: 1730, width: 300, height: 164, label: 'CHECKSUM FROM BLUE MERCY' },
		],
	},
];
