import type { NpcScheduleRule } from './WorldSchedule';

export const LATE_ACT_SCHEDULE_RULES: readonly NpcScheduleRule[] = [
	{
		npcId: 'reverend-null-dial',
		locationId: 'antenna-barrens:safehouse',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 46,
	},
	{
		npcId: 'maceo-margin',
		locationId: 'antenna-barrens:settlement',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 47,
	},
	{
		npcId: 'maceo-margin',
		locationId: 'antenna-barrens:station',
		fromBeat: 'homecoming',
		priority: 58,
	},
	{
		npcId: 'doctor-error-bar',
		locationId: 'antenna-barrens:settlement',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 46,
	},
	{
		npcId: 'penny-static',
		locationId: 'antenna-barrens:station',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 46,
	},
	{
		npcId: 'calder-raincheck',
		locationId: 'antenna-barrens:station',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 46,
	},
	{
		npcId: 'mara-modulo',
		locationId: 'antenna-barrens:settlement',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 47,
	},
	{
		npcId: 'black-ice-fox',
		locationId: 'antenna-barrens:station',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 48,
		requiresWorldFlags: ['antenna-barrens:public-forecast'],
	},
	{
		npcId: 'matron-counterweight',
		locationId: 'orbital-lift:safehouse',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 49,
	},
	{
		npcId: 'esme-manifest',
		locationId: 'orbital-lift:settlement',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 49,
	},
	{
		npcId: 'brother-ballast',
		locationId: 'orbital-lift:settlement',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'homecoming',
		priority: 49,
	},
	{
		npcId: 'elevator-angel',
		locationId: 'orbital-lift:station',
		fromBeat: 'public-forecast',
		untilBeatExclusive: 'last-route',
		priority: 50,
	},
	{
		npcId: 'rita-latch',
		locationId: 'orbital-lift:station',
		fromBeat: 'public-forecast',
		priority: 54,
	},
	{
		npcId: 'choir-of-static',
		locationId: 'asteroid-redoubt:safehouse',
		fromBeat: 'last-route',
		untilBeatExclusive: 'commons-dawn',
		priority: 70,
	},
	{
		npcId: 'aunt-aster',
		locationId: 'asteroid-redoubt:safehouse',
		fromBeat: 'last-route',
		priority: 70,
	},
	{
		npcId: 'witness-zero',
		locationId: 'asteroid-redoubt:settlement',
		fromBeat: 'last-route',
		untilBeatExclusive: 'commons-dawn',
		priority: 70,
	},
	{
		npcId: 'little-ix',
		locationId: 'asteroid-redoubt:settlement',
		fromBeat: 'last-route',
		untilBeatExclusive: 'commons-dawn',
		priority: 72,
	},
	{
		npcId: 'return-signal-sam',
		locationId: 'asteroid-redoubt:station',
		fromBeat: 'last-route',
		priority: 70,
	},
	{
		npcId: 'director-vane',
		locationId: 'asteroid-redoubt:settlement',
		fromBeat: 'last-route',
		untilBeatExclusive: 'commons-dawn',
		priority: 75,
	},
	{
		npcId: 'della-redact',
		locationId: 'asteroid-redoubt:settlement',
		fromBeat: 'last-route',
		untilBeatExclusive: 'commons-dawn',
		priority: 74,
	},
	{
		npcId: 'della-redact',
		locationId: 'asteroid-redoubt:station',
		fromBeat: 'commons-dawn',
		priority: 84,
	},
	{
		npcId: 'choir-of-static',
		locationId: 'lower-sprawl:station',
		fromBeat: 'commons-dawn',
		priority: 82,
	},
	{
		npcId: 'witness-zero',
		locationId: 'drainmarket:settlement',
		fromBeat: 'commons-dawn',
		priority: 82,
	},
];
