import type { InfrastructureLinkDef, InfrastructureNodeDef } from './InfrastructureNetwork';

export const LATE_ACT_INFRASTRUCTURE_NODES: readonly InfrastructureNodeDef[] = [
	{
		id: 'listener-consent-archive',
		districtId: 'antenna-barrens',
		kind: 'archive',
		label: 'Consent-Aware Listener Archive',
		description: 'Suppressed warnings with chosen audience, protected identity, expiry, withdrawal, and distributed custody.',
		operationalFlag: 'penny-opened-listener-cache',
		commonsFlag: 'antenna-barrens:listener-cache-public',
	},
	{
		id: 'forecast-appeal-switch',
		districtId: 'antenna-barrens',
		kind: 'signal',
		label: 'Pre-Harm Forecast Appeal Switch',
		description: 'A physical and procedural delay path that pauses automated priority while affected people object.',
		operationalFlag: 'error-bar-opened-appeal-table',
		commonsFlag: 'antenna-barrens:pre-harm-appeals',
	},
	{
		id: 'passenger-manifest-network',
		districtId: 'orbital-lift',
		kind: 'transit',
		label: 'Passenger Manifest Network',
		description: 'Descent capacity, care, protected witnesses, seeds, tools, refusal windows, and correction history.',
		operationalFlag: 'esme-opened-witness-manifest',
		commonsFlag: 'orbital-lift:passenger-manifest',
	},
	{
		id: 'angel-command-history',
		districtId: 'orbital-lift',
		kind: 'archive',
		label: 'Interruptible Command-History Port',
		description: 'Order authors, affected passengers, mercy exceptions, refusal grounds, and delay costs before execution.',
		operationalFlag: 'angel-admitted-mercy-exceptions',
		commonsFlag: 'orbital-lift:angel-refusal-public',
	},
	{
		id: 'public-toolkit-mirrors',
		districtId: 'asteroid-redoubt',
		kind: 'archive',
		label: 'Public Toolkit Mirrors',
		description: 'Dismantling tools, maintenance scores, legal templates, and local copies beyond the final transmitter.',
		operationalFlag: 'witness-zero-opened-toolkit-case',
		commonsFlag: 'asteroid-redoubt:public-toolkits-distributed',
	},
	{
		id: 'protected-route-map',
		districtId: 'asteroid-redoubt',
		kind: 'archive',
		label: 'Accountable Protected-Route Map',
		description: 'Visible blanks with disclosure rules, witnesses, refusal, emergency access, revision, and expiry.',
		operationalFlag: 'little-ix-opened-protected-map',
		commonsFlag: 'asteroid-redoubt:protected-map-public',
	},
	{
		id: 'peer-return-signal',
		districtId: 'asteroid-redoubt',
		kind: 'transit',
		label: 'Peer Return and Revision Signal',
		description: 'City, colony, and asteroid availability, uncertainty, maintenance limits, and refusal without a central interchange.',
		operationalFlag: 'asteroid-redoubt:story-complete',
		commonsFlag: 'main:commons-line',
	},
];

export const LATE_ACT_INFRASTRUCTURE_LINKS: readonly InfrastructureLinkDef[] = [
	{
		id: 'dogear-archive-to-listener-consent',
		fromNodeId: 'dogear-route-archive',
		toNodeId: 'listener-consent-archive',
		label: 'Consent and deliberate ambiguity travel upward',
		message: 'Drainmarket archive practice teaches the listener cache to preserve warnings without exposing every route or identity.',
		requiresFromStatus: 'operational',
		requiresToDiscovered: true,
	},
	{
		id: 'refusal-archive-to-listener-consent',
		fromNodeId: 'refusal-archive-network',
		toNodeId: 'listener-consent-archive',
		label: 'Withdrawable testimony reaches the forecast',
		message: 'Mirror Palace withdrawal rights prevent recovered listener speech from becoming permanent public property.',
		requiresFromStatus: 'operational',
		requiresToDiscovered: true,
	},
	{
		id: 'listener-consent-to-public-forecast',
		fromNodeId: 'listener-consent-archive',
		toNodeId: 'public-forecast-array',
		label: 'Sentences return to movement data',
		message: 'The forecast displays listener warnings with consent and context instead of keeping movement while deleting speech.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'public-forecast-to-appeal-switch',
		fromNodeId: 'public-forecast-array',
		toNodeId: 'forecast-appeal-switch',
		label: 'Prediction can be delayed before harm',
		message: 'Every automated route or enforcement change exposes a human appeal window before execution.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'colony-air-to-passenger-manifest',
		fromNodeId: 'colony-air-forecast',
		toNodeId: 'passenger-manifest-network',
		label: 'Breathing conditions enter descent capacity',
		message: 'Passenger capacity carries air pressure, medical exceptions, confidence, and objections from the colony forecast.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'return-line-to-passenger-manifest',
		fromNodeId: 'bidirectional-return-line',
		toNodeId: 'passenger-manifest-network',
		label: 'The colony keeps interruption rights during descent',
		message: 'The Lift cannot convert a peer connection into annexation or one-way evacuation.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'listener-consent-to-passenger-manifest',
		fromNodeId: 'listener-consent-archive',
		toNodeId: 'passenger-manifest-network',
		label: 'Protected witnesses board without becoming cargo metadata',
		message: 'Passenger records inherit audience, alias, expiry, and withdrawal rules from the listener archive.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'appeal-switch-to-passenger-manifest',
		fromNodeId: 'forecast-appeal-switch',
		toNodeId: 'passenger-manifest-network',
		label: 'Classification can pause before routing',
		message: 'A passenger may challenge freight classification before the Lift moves them.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'passenger-manifest-to-homecoming-lift',
		fromNodeId: 'passenger-manifest-network',
		toNodeId: 'homecoming-lift',
		label: 'Cargo declares itself passengers',
		message: 'The downbound Lift carries people, care, testimony, seeds, and tools through a correctable passenger manifest.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'angel-history-to-homecoming-lift',
		fromNodeId: 'angel-command-history',
		toNodeId: 'homecoming-lift',
		label: 'Orders travel with authors and refusal grounds',
		message: 'Every descent order names its author, affected passengers, challenge path, and delay cost.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'blue-mercy-to-public-toolkit-mirrors',
		fromNodeId: 'blue-mercy-line',
		toNodeId: 'public-toolkit-mirrors',
		label: 'The final launch carries practiced tools',
		message: 'Blue Mercy sends maintenance, legal, routing, and refusal practices—not only heroes—to the Redoubt.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'protected-map-to-peer-return-signal',
		fromNodeId: 'protected-route-map',
		toNodeId: 'peer-return-signal',
		label: 'Connection without universal access',
		message: 'The return signal can prove protected routes exist without revealing coordinates that would destroy them.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'toolkit-mirrors-to-commons-transmitter',
		fromNodeId: 'public-toolkit-mirrors',
		toNodeId: 'commons-transmitter',
		label: 'The broadcast includes methods and local copies',
		message: 'The final message teaches how to reproduce, maintain, challenge, and revise the change.',
		requiresFromStatus: 'commons',
		requiresToDiscovered: true,
	},
	{
		id: 'peer-return-to-commons-transmitter',
		fromNodeId: 'peer-return-signal',
		toNodeId: 'commons-transmitter',
		label: 'Receiving stations can answer back',
		message: 'City, colony, and asteroid can revise or refuse the final doctrine instead of only receiving it.',
		requiresFromStatus: 'operational',
		requiresToDiscovered: true,
	},
	{
		id: 'commons-transmitter-to-blue-mercy',
		fromNodeId: 'commons-transmitter',
		toNodeId: 'blue-mercy-line',
		label: 'The last route returns as a maintenance commons',
		message: 'Evidence, tools, protected maps, and revision authority mirror back into the subway rather than remaining at the frontier.',
		requiresFromStatus: 'commons',
	},
];
