import type { SocialSpaceLayoutDef } from './SocialSpaceCatalog';

export const ORBITAL_LIFT_SOCIAL_SPACES: readonly SocialSpaceLayoutDef[] = [
	{
		locationId: 'orbital-lift:safehouse',
		width: 1980,
		floorY: 356,
		spawnX: 170,
		walkSpeed: 210,
		interactionRadius: 92,
		farLayer: 'Counterweight cables descend through a window toward the city far below.',
		midLayer: 'Soup tables, bunk boards, union keys, passenger names, medical crates, and porter gear fill the galley.',
		anchors: [
			{ id: 'matron-counterweight', kind: 'npc', x: 320 },
			{ id: 'clinic', kind: 'service', x: 510 },
			{ id: 'rumor-board', kind: 'service', x: 760 },
			{ id: 'brother-ballast', kind: 'npc', x: 1040 },
			{ id: 'repair-bench', kind: 'service', x: 1240 },
			{ id: 'lio-vale', kind: 'npc', x: 1510 },
			{ id: 'loadout-locker', kind: 'service', x: 1760 },
		],
		props: [
			{ id: 'downbound-table', kind: 'bench', x: 230, width: 430, height: 108, label: 'SOUP BEFORE CONSTITUTION' },
			{ id: 'bunk-board', kind: 'archive', x: 690, width: 300, height: 152, label: 'FREIGHT THAT SNORES' },
			{ id: 'union-bench', kind: 'bench', x: 1170, width: 260, height: 98, label: 'LOAD / LABOR / DELAY' },
			{ id: 'customs-repair', kind: 'archive', x: 1450, width: 270, height: 142, label: 'CONFESSION → ROUTE WORK' },
		],
	},
	{
		locationId: 'orbital-lift:settlement',
		width: 2280,
		floorY: 358,
		spawnX: 180,
		walkSpeed: 214,
		interactionRadius: 96,
		farLayer: 'Cargo lanes and passenger platforms rise through a vertical customs cathedral.',
		midLayer: 'Inside-out customs desks, witness containers, porter harnesses, claim stamps, tickets, and cityward windows occupy the concourse.',
		anchors: [
			{ id: 'esme-manifest', kind: 'npc', x: 320 },
			{ id: 'archive', kind: 'service', x: 510 },
			{ id: 'legal-aid', kind: 'service', x: 760 },
			{ id: 'brother-ballast', kind: 'npc', x: 1050 },
			{ id: 'field-shop', kind: 'service', x: 1250 },
			{ id: 'portia-drift', kind: 'npc', x: 1540 },
			{ id: 'lio-vale', kind: 'npc', x: 1770 },
			{ id: 'ames-oxygen', kind: 'npc', x: 2040 },
		],
		props: [
			{ id: 'claim-wall', kind: 'archive', x: 230, width: 390, height: 172, label: 'CLAIM ≠ BREATHING' },
			{ id: 'appeal-desk', kind: 'bench', x: 690, width: 250, height: 102, label: 'CLASSIFICATION APPEAL' },
			{ id: 'passenger-coop', kind: 'stall', x: 1130, width: 270, height: 128, label: 'SEIZED STOCK / ORIGINAL OWNER' },
			{ id: 'hidden-transfer', kind: 'train', x: 1470, width: 340, height: 142, label: 'STAFF LOCAL CONNECTION' },
			{ id: 'air-capacity', kind: 'console', x: 1970, width: 220, height: 156, label: 'BREATH / DESCENT' },
		],
	},
	{
		locationId: 'orbital-lift:station',
		width: 2200,
		floorY: 360,
		spawnX: 190,
		walkSpeed: 222,
		interactionRadius: 100,
		farLayer: 'Counterweights and cable wings vanish upward and downward through the lift shaft.',
		midLayer: 'Order glass, passenger platforms, command-history ports, descent controls, and manual brake rigs line the elevator nave.',
		anchors: [
			{ id: 'elevator-angel', kind: 'npc', x: 330 },
			{ id: 'rita-latch', kind: 'npc', x: 520 },
			{ id: 'transit-control', kind: 'service', x: 700 },
			{ id: 'esme-manifest', kind: 'npc', x: 940 },
			{ id: 'archive', kind: 'service', x: 1160 },
			{ id: 'portia-drift', kind: 'npc', x: 1430 },
			{ id: 'old-quasar-jones', kind: 'npc', x: 1680 },
			{ id: 'repair-bench', kind: 'service', x: 1910 },
			{ id: 'signal-lab', kind: 'service', x: 2100 },
		],
		props: [
			{ id: 'angel-order-glass', kind: 'console', x: 250, width: 420, height: 190, label: 'ORDER / AUTHOR / HARM' },
			{ id: 'passenger-platform', kind: 'train', x: 760, width: 430, height: 148, label: 'CARGO DECLARES ITSELF PASSENGERS' },
			{ id: 'command-history', kind: 'archive', x: 1210, width: 290, height: 168, label: 'REFUSAL GROUNDS' },
			{ id: 'manual-brakes', kind: 'bench', x: 1760, width: 300, height: 108, label: 'THREE REPLACEMENT CREWS' },
		],
	},
];
