import type { CombatEntity } from '../systems/CombatSystem';
import type { Pickup } from '../systems/ItemSystem';
import type { Platform } from '../systems/PhysicsSystem';
import type { StageLayout } from './lowerSprawlLayout';

const platforms: Platform[] = [
	{ x: 0, y: 494, w: 2320, h: 80 },
	{ x: 180, y: 420, w: 170, h: 18 },
	{ x: 390, y: 350, w: 210, h: 18 },
	{ x: 670, y: 410, w: 170, h: 18 },
	{ x: 900, y: 325, w: 230, h: 18 },
	{ x: 1190, y: 392, w: 190, h: 18 },
	{ x: 1450, y: 330, w: 180, h: 18 },
	{ x: 1690, y: 420, w: 170, h: 18 },
	{ x: 1880, y: 430, w: 350, h: 18 },
];

const pickups: Pickup[] = [
	{
		id: 'arcology_railgun_issue',
		itemId: 'railgun',
		x: 245,
		y: 382,
		kind: 'railgun',
		radius: 34,
		taken: false,
		visualState: 'available',
		animation: 'railgun_pickup',
		persistence: 'saved_once',
	},
	{
		id: 'arcology_stim_service',
		itemId: 'stim_pack',
		x: 720,
		y: 372,
		kind: 'stim',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'stim_pack_pickup',
		persistence: 'ephemeral',
	},
	{
		id: 'arcology_mirror_thread',
		itemId: 'mirror_thread',
		x: 1510,
		y: 295,
		kind: 'gear',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'mirror_thread_pickup',
		spriteSheetId: 'items_extended',
		persistence: 'saved_once',
	},
	{
		id: 'arcology_shock_fern',
		itemId: 'shock_fern',
		x: 1810,
		y: 385,
		kind: 'gear',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'shock_fern_pickup',
		spriteSheetId: 'items_extended',
		persistence: 'saved_once',
	},
	{
		id: 'arcology_mutual_aid_capacitor',
		itemId: 'capacitor_coil',
		x: 470,
		y: 315,
		kind: 'gear',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'capacitor_coil_pickup',
		spriteSheetId: 'items_extended',
		persistence: 'saved_once',
	},
	{
		id: 'arcology_rail_heat_sink',
		itemId: 'rail_heat_sink',
		x: 970,
		y: 290,
		kind: 'gear',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'rail_heat_sink_pickup',
		spriteSheetId: 'items_extended',
		persistence: 'saved_once',
	},
	{
		id: 'arcology_stim_gallery',
		itemId: 'stim_pack',
		x: 1510,
		y: 292,
		kind: 'stim',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'stim_pack_pickup',
		persistence: 'ephemeral',
	},
	{
		id: 'chrome-arcology_elevator_seed_payload',
		itemId: 'elevator_seed',
		x: 2180,
		y: 392,
		kind: 'story_payload',
		radius: 32,
		taken: false,
		visualState: 'available',
		animation: 'elevator_seed_pickup',
		persistence: 'story_payload',
	},
];

const enemies: CombatEntity[] = [
	{
		id: 'chrome-bellhop-atrium',
		x: 560,
		y: 446,
		w: 42,
		h: 48,
		vx: -34,
		vy: 0,
		dir: -1,
		onGround: true,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 3,
		maxHp: 3,
		armor: 0.15,
		stun: 0,
		invuln: 0,
		procgenFamily: 'chrome_bellhop',
		procgenRole: 'bruiser',
	},
	{
		id: 'mirror-sentinel-cargo',
		x: 1040,
		y: 277,
		w: 42,
		h: 48,
		vx: 0,
		vy: 0,
		dir: -1,
		onGround: true,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 3,
		maxHp: 3,
		armor: 0.2,
		stun: 0,
		invuln: 0,
		procgenFamily: 'mirror_sentinel',
		procgenRole: 'ranged',
	},
	{
		id: 'chrome-bellhop-gallery',
		x: 1370,
		y: 446,
		w: 42,
		h: 48,
		vx: 28,
		vy: 0,
		dir: 1,
		onGround: true,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 4,
		maxHp: 4,
		armor: 0.2,
		stun: 0,
		invuln: 0,
		procgenFamily: 'chrome_bellhop',
		procgenRole: 'bruiser',
	},
	{
		id: 'mirror-sentinel-vault',
		x: 1730,
		y: 372,
		w: 42,
		h: 48,
		vx: 0,
		vy: 0,
		dir: -1,
		onGround: true,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 4,
		maxHp: 4,
		armor: 0.2,
		stun: 0,
		invuln: 0,
		procgenFamily: 'mirror_sentinel',
		procgenRole: 'ranged',
	},
];

export const chromeArcologyLayout: StageLayout = {
	id: 'chrome-arcology-runtime',
	platforms,
	pickups,
	enemies,
};

export function cloneChromeArcologyLayout(): StageLayout {
	return {
		id: chromeArcologyLayout.id,
		platforms: chromeArcologyLayout.platforms.map((platform) => ({ ...platform })),
		pickups: chromeArcologyLayout.pickups.map((pickup) => ({ ...pickup })),
		enemies: chromeArcologyLayout.enemies.map((enemy) => ({ ...enemy })),
	};
}
