import type { CombatEntity } from '../systems/CombatSystem';
import type { Pickup } from '../systems/ItemSystem';
import type { Platform } from '../systems/PhysicsSystem';
import type { StageLayout } from './lowerSprawlLayout';

const platforms: Platform[] = [
	{ x: 0, y: 494, w: 2020, h: 80 },
	{ x: 210, y: 418, w: 150, h: 18 },
	{ x: 430, y: 355, w: 145, h: 18 },
	{ x: 665, y: 405, w: 160, h: 18 },
	{ x: 900, y: 340, w: 185, h: 18 },
	{ x: 1160, y: 410, w: 170, h: 18 },
	{ x: 1380, y: 365, w: 145, h: 18 },
	{ x: 1540, y: 430, w: 380, h: 18 },
];

const pickups: Pickup[] = [
	{
		id: 'drainmarket_railgun_cache',
		itemId: 'railgun',
		x: 475,
		y: 320,
		kind: 'railgun',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'railgun_pickup',
		persistence: 'saved_once',
	},
	{
		id: 'drainmarket_stim_west',
		itemId: 'stim_pack',
		x: 705,
		y: 370,
		kind: 'stim',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'stim_pack_pickup',
		persistence: 'ephemeral',
	},
	{
		id: 'drainmarket_ledger_lens',
		itemId: 'ledger_lens',
		x: 1250,
		y: 375,
		kind: 'gear',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'ledger_lens_pickup',
		spriteSheetId: 'items_extended',
		persistence: 'saved_once',
	},
	{
		id: 'drainmarket_phase_mantle',
		itemId: 'phase_mantle',
		x: 315,
		y: 383,
		kind: 'gear',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'phase_mantle_pickup',
		spriteSheetId: 'items_extended',
		persistence: 'saved_once',
	},
	{
		id: 'drainmarket_katana_cache',
		itemId: 'katana',
		x: 960,
		y: 304,
		kind: 'katana',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'katana_pickup',
		persistence: 'saved_once',
	},
	{
		id: 'drainmarket_stim_clinic',
		itemId: 'stim_pack',
		x: 1420,
		y: 330,
		kind: 'stim',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'stim_pack_pickup',
		persistence: 'ephemeral',
	},
	{
		id: 'drainmarket_stim_cache_payload',
		itemId: 'stim_cache',
		x: 1880,
		y: 395,
		kind: 'story_payload',
		radius: 30,
		taken: false,
		visualState: 'available',
		animation: 'stim_cache_pickup',
		persistence: 'story_payload',
	},
];

const enemies: CombatEntity[] = [
	{
		id: 'knife-drone-west',
		x: 560,
		y: 405,
		w: 36,
		h: 34,
		vx: -48,
		vy: 0,
		dir: -1,
		onGround: false,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 2,
		maxHp: 2,
		stun: 0,
		invuln: 0,
		procgenFamily: 'knife_drone',
		procgenRole: 'skirmisher',
	},
	{
		id: 'price-wasp-clinic',
		x: 850,
		y: 390,
		w: 34,
		h: 32,
		vx: 42,
		vy: 0,
		dir: 1,
		onGround: false,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 2,
		maxHp: 2,
		stun: 0,
		invuln: 0,
		procgenFamily: 'price_tag_wasp',
		procgenRole: 'ranged',
	},
	{
		id: 'clinic-collector-east',
		x: 1215,
		y: 458,
		w: 42,
		h: 36,
		vx: -28,
		vy: 0,
		dir: -1,
		onGround: true,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 4,
		maxHp: 4,
		armor: 0.2,
		stun: 0,
		invuln: 0,
		procgenFamily: 'clinic_collector',
		procgenRole: 'bruiser',
	},
	{
		id: 'knife-drone-nest-guard',
		x: 1470,
		y: 400,
		w: 36,
		h: 34,
		vx: 0,
		vy: 0,
		dir: -1,
		onGround: false,
		coyoteLeft: 0,
		jumpBuffered: 0,
		hp: 3,
		maxHp: 3,
		stun: 0,
		invuln: 0,
		procgenFamily: 'knife_drone',
		procgenRole: 'skirmisher',
	},
];

export const drainmarketLayout: StageLayout = {
	id: 'drainmarket-runtime',
	platforms,
	pickups,
	enemies,
};

export function cloneDrainmarketLayout(): StageLayout {
	return {
		id: drainmarketLayout.id,
		platforms: drainmarketLayout.platforms.map((platform) => ({ ...platform })),
		pickups: drainmarketLayout.pickups.map((pickup) => ({ ...pickup })),
		enemies: drainmarketLayout.enemies.map((enemy) => ({ ...enemy })),
	};
}
