import type { CombatEntity } from '../systems/CombatSystem';
import type { Pickup } from '../systems/ItemSystem';
import type { Platform } from '../systems/PhysicsSystem';

export interface StageLayout {
	id: string;
	platforms: Platform[];
	pickups: Pickup[];
	enemies: CombatEntity[];
}

export const lowerSprawlLayout: StageLayout = {
	id: 'lower-sprawl-prototype',
	platforms: [
		{ x: 0, y: 494, w: 1900, h: 80 },
		{ x: 230, y: 415, w: 135, h: 18 },
		{ x: 455, y: 360, w: 130, h: 18 },
		{ x: 705, y: 405, w: 150, h: 18 },
		{ x: 950, y: 338, w: 170, h: 18 },
		{ x: 1230, y: 420, w: 160, h: 18 },
		{ x: 1480, y: 365, w: 240, h: 18 },
	],
	pickups: [
		{
			id: 'rocket_backpack',
			itemId: 'rocket_backpack',
			x: 270,
			y: 382,
			kind: 'rocket',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'rocket_backpack_pickup',
			persistence: 'saved_once',
		},
		{
			id: 'railgun',
			itemId: 'railgun',
			x: 500,
			y: 326,
			kind: 'railgun',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'railgun_pickup',
			persistence: 'saved_once',
		},
		{
			id: 'stim_pack',
			itemId: 'stim_pack',
			x: 996,
			y: 304,
			kind: 'stim',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'stim_pack_pickup',
			persistence: 'ephemeral',
		},
		{
			id: 'bassline_boots_route',
			itemId: 'bassline_boots',
			x: 782,
			y: 370,
			kind: 'set_piece',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'bassline_boots_pickup',
			persistence: 'saved_once',
		},
		{
			id: 'gravity_talisman_route',
			itemId: 'gravity_talisman',
			x: 1305,
			y: 385,
			kind: 'set_piece',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'gravity_talisman_pickup',
			persistence: 'saved_once',
		},
		{
			id: 'echo_spurs_route',
			itemId: 'echo_spurs',
			x: 1080,
			y: 303,
			kind: 'set_piece',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'echo_spurs_pickup',
			spriteSheetId: 'items_extended',
			persistence: 'saved_once',
		},
		{
			id: 'rootkit_badge_route',
			itemId: 'rootkit_badge',
			x: 1370,
			y: 385,
			kind: 'gear',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'rootkit_badge_pickup',
			spriteSheetId: 'items_extended',
			persistence: 'saved_once',
		},
		{
			id: 'katana',
			itemId: 'katana',
			x: 1518,
			y: 330,
			kind: 'katana',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'katana_pickup',
			persistence: 'saved_once',
		},
		{
			id: 'wafer_key_payload',
			itemId: 'wafer_key',
			x: 1688,
			y: 330,
			kind: 'story_payload',
			radius: 30,
			taken: false,
			visualState: 'available',
			animation: 'wafer_key_pickup',
			persistence: 'story_payload',
		},
	],
	enemies: [
		{
			id: 'toll-scooter-west',
			x: 620,
			y: 462,
			w: 34,
			h: 32,
			vx: -42,
			vy: 0,
			dir: -1,
			onGround: true,
			coyoteLeft: 0,
			jumpBuffered: 0,
			hp: 2,
			maxHp: 2,
			stun: 0,
			invuln: 0,
			procgenFamily: 'toll-scooter',
			procgenRole: 'patrol',
		},
		{
			id: 'meter-enforcer-market',
			x: 1130,
			y: 305,
			w: 34,
			h: 30,
			vx: 0,
			vy: 0,
			dir: -1,
			onGround: true,
			coyoteLeft: 0,
			jumpBuffered: 0,
			hp: 2,
			maxHp: 2,
			stun: 0,
			invuln: 0,
			procgenFamily: 'meter-enforcer',
			procgenRole: 'turret',
		},
		{
			id: 'receipt-crawler-east',
			x: 1180,
			y: 462,
			w: 38,
			h: 32,
			vx: 36,
			vy: 0,
			dir: 1,
			onGround: true,
			coyoteLeft: 0,
			jumpBuffered: 0,
			hp: 3,
			maxHp: 3,
			stun: 0,
			invuln: 0,
			armor: 0.25,
			procgenFamily: 'receipt-crawler',
			procgenRole: 'bruiser',
		},
	],
};

export function cloneLowerSprawlLayout(): StageLayout {
	return {
		id: lowerSprawlLayout.id,
		platforms: lowerSprawlLayout.platforms.map((platform) => ({ ...platform })),
		pickups: lowerSprawlLayout.pickups.map((pickup) => ({ ...pickup })),
		enemies: lowerSprawlLayout.enemies.map((enemy) => ({ ...enemy })),
	};
}
